### ISSUE TITLE
Typo in struct member name

### ISSUE THREAD

**Issue by bobveznat** [greenpau/go-cisco-nx-api#1]
Thanks for putting together this package. I went to start using the Bios version in some code I'm writing and noticed that it got typo'ed Verion. Hardly a huge deal, easy to work around. But wanted to point it out. Thanks again for creating this.

https://github.com/greenpau/go-cisco-nx-api/blob/41ff27c0a947a31fd050bc9f9927fe2a9c6d7dfb/pkg/client/sysinfo.go#L62

**Comment by greenpau** [comment]
> Thanks for putting together this package. 

@bobveznat, hope you are having fun with it! 😄 

> I went to start using the Bios version in some code I'm writing and noticed that it got typo'ed Verion.

@bobveznat , thank you for reporting this! It is a bug!

**Comment by greenpau** [comment]
@bobveznat , fixed 😄

**Comment by greenpau** [comment]
@bobveznat , I would appreciate a star on the project and mention on LinkedIn 😄
