### ISSUE TITLE
support configuration

### ISSUE THREAD

**Issue by tao-sj** [greenpau/go-cisco-nx-api#2]
Hi Paul,

Your code looks a good start to support NX API.
Do you have plan to support switches configuration commands ?

Thanks,
Tao

**Comment by greenpau** [comment]
@tao-sj , I think it is easy to extend the library to perform configuration. The existing methods for the module create a pattern allowing the extension.

**Comment by tao-sj** [comment]
yes, if you are not, I'd like to extend it and merge into your repo.

Tao

**Comment by greenpau** [comment]
> yes, if you are not, I'd like to extend it and merge into your repo.

Sure, just open PR.

**Comment by tao-sj** [comment]
https://github.com/greenpau/go-cisco-nx-api/pull/3

**Comment by greenpau** [comment]
@tao-sj , thank you for the contribution! 🏆 Now, its time for 🍻
